services:
  driven_ops_db:
    image: postgres
    container_name: driven_ops_db
    restart: always
    ports:
      - 2345:5432
    volumes:
      - driven_ops_db:/var/lib/postgresql/data
    env_file:
      - back-end/.env


  driven_ops_app:
    container_name: driven_ops_app
    build: ./back-end #dockerfile do back
    ports:
      - 5000:5000
    depends_on:
      - driven_ops_db
    env_file:
      - back-end/.env


      
  react_driven_ops_app:
    container_name: react_driven_ops_app
    build: ./front-end #dockerfile do front
    volumes:
      - build_react:/var/www/html

  
  nginx_driven_ops_app:
    container_name: nginx_driven_ops_app
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - driven_ops_db
      - driven_ops_app
      - react_driven_ops_app

volumes:
  driven_ops_db:
  build_react: