services:
  driven_ops_db_tests:
    image: postgres
    container_name: driven_ops_db_tests
    restart: always
    ports:
      - 2345:5432
    env_file:
      - back-end/.env.test
  driven_ops_app:
    container_name: driven_ops_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - driven_ops_db_tests
    env_file:
      - back-end/.env.test