services:
  driven_ops_db:
    image: postgres
    container_name: driven_ops_db
    restart: always
    ports:
      - 2345:5432
    volumes:
      - driven_ops_db:/var/lib/postgresql/data
    env_file:
      - .env
  driven_ops_app:
    container_name: driven_ops_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - driven_ops_db
    env_file:
      - .env

volumes:
  driven_ops_db: