# name: Deploy on AWS
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     name: Deploy to EC2
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the files
#         uses: actions/checkout@v3
#       - name: Deploy to Server 1
#         uses: easingthemes/ssh-deploy@main
#         env:
#           SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
#           REMOTE_HOST: ${ { secrets.HOST_DNS }}
#           REMOTE_USER: ${ { secrets.USERNAME }}
#           TARGET: ${ { secrets.TARGET_DIR }}

name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create back-end envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          directory: back-end/
          file_name: ".env"
          fail_on_empty: true


      - name: Create front-end envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_UR}}
          directory: front-end/
          file_name: ".env"
          fail_on_empty: true

      - name: Build
        run: docker-compose build
      
      - name: Run
        run: docker-compose down && docker-compose up -d